import { z } from "zod";

// TODO: unite with auth schema
export const IdentitySchema = z
    .string()
    .regex(/^[a-z0-9._-]+@[a-z0-9.-]+(:\d+)?$/, "Expected a lowercase identity like foo@bar.com");

// uppercase ULID, generated by the uploader so the post url is known before the host has published it, and sortable by time
export const PostIDSchema = z
    .string()
    .regex(/^[0-7][0-9A-HJKMNP-TV-Z]{25}$/, "Expected an uppercase ULID");

export const MAX_CAPTION_LENGTH = 512;
export const CaptionSchema = z.string().min(1).max(MAX_CAPTION_LENGTH);

export const Sha256HexSchema = z.string().regex(/^[0-9a-f]{64}$/, "Expected a lowercase hex sha256 digest");

export const URLSchema = z.url({
    protocol: /^https?$/,
    message: "Expected an http or https url"
});

